json_path: the_path_for_data/data.json
fold: 2
save_folder: ./fold2/
resume: -1
baselr: 0.001
gpu_id: 0
pretrain:  
inchannel: 1
num_class: 1
dataset: npyDataSet_2d_v3_2D
batch_size: 1
network: XUnet #unet, resunet, XUnet
num_image: 32
