json_path: /home/kui/Qikui/CBCT_Task/Code/data.json
fold: 2
save_folder: ./XUnet1/fold2/
resume: -1
baselr: 0.001
gpu_id: 0
pretrain:  /home/kui/Qikui/CBCT_Task/Code/XUnet/fold2/45500_stage_one.pth
inchannel: 1
num_class: 1
dataset: npyDataSet_2d_v3_2D
batch_size: 1
network: XUnet #unet, resunet, XUnet
num_image: 32